### ISSUE TITLE
URLのコピーのinputタグを消す。

### ISSUE THREAD

**Issue by t-aburasoba** [masagao/potfy#109]
# やること
- [x] urlコピーのinputタグを隠したい
https://qiita.com/rico/items/0f645e84028d4fe00be6

# 完了の定義
-

**Comment by t-aburasoba** [comment]
visibility:hidden
を付与すると、コピーできなくなる模様。
display:noneも同様。
要調査

**Comment by masagao** [comment]
すみません、これ非表示になるとコピーできないのか。。
① https://stackoverflow.com/questions/49053240/hidden-element-wont-copy-to-clipboard
② https://t-shukujo.com/hidden-input-to-clipboard/

**Comment by t-aburasoba** [comment]
ありがとうございます🙇‍♂️
