### ISSUE TITLE
Story コメント は UpdateOrCreate で実装したい

### ISSUE THREAD

**Issue by masagao** [masagao/potfy#185]
# やること
- [x] 現状、Story コメント において、開発理由等を 2個以上投稿できるようになっているが、こちらは、再度投稿理由が投稿された場合、以前のものを更新する形で実装したい。
- [x] ストーリーが投稿された時に、投稿しました等のメッセージを表示できるようにしたい

# 完了の定義
- Story コメント は UpdateOrCreate で実装したい

**Comment by t-aburasoba** [comment]
https://readouble.com/laravel/6.x/ja/eloquent.html
