### ISSUE TITLE
投稿されたアプリの詳細に改行があった場合、詳細画面でも改行したい

### ISSUE THREAD

**Issue by masagao** [masagao/potfy#186]
# やること
- [ ] 現状、アプリの詳細画面に表示される詳細内容は、文字が詰まってしまっていて、改行がされていない。投稿時点で、改行しているような場合は、その通りに改行できるようにしたい

# 完了の定義
- 投稿されたアプリの詳細に改行があった場合、詳細画面でも改行したい

**Comment by t-aburasoba** [comment]
https://qiita.com/PKunito/items/e4a8273ebce267311690
